FROM java:latest
ADD MessageStreamMicroServices_v2/createSwiftMessage-impl/target/universal /tmp/
RUN unzip /tmp/createswiftmessage-impl-1.0-SNAPSHOT.zip
ENTRYPOINT ["createswiftmessage-impl-1.0-SNAPSHOT/bin/createswiftmessage-impl"]
CMD []